id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-03-10T18:24:27.100Z
blockData:
  top: 48
  left: 48
  uuid: 2f94276c-b2d5-464e-87b0-24a25eed9617
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
